/**
 * MAN Trucks
 * Esta é a definição da API para o code challenge
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Truck { 
    id?: number;
    name: string;
    engineHP: number;
    engineVolume: number;
    fuel?: string;
    segments?: Array<Truck.SegmentsEnum>;
    colors: Array<string>;
}
export namespace Truck {
    export type SegmentsEnum = 'Long Haul' | 'Construction' | 'Firedepartment' | 'Distribution (Food)' | 'Wastedisposal';
    export const SegmentsEnum = {
        LongHaul: 'Long Haul' as SegmentsEnum,
        Construction: 'Construction' as SegmentsEnum,
        Firedepartment: 'Firedepartment' as SegmentsEnum,
        DistributionFood: 'Distribution (Food)' as SegmentsEnum,
        Wastedisposal: 'Wastedisposal' as SegmentsEnum
    };
}