DELETE FROM TRUCK WHERE 1=1;

INSERT INTO TRUCK (ID, NAME, ENGINE_HP, ENGINE_VOLUME, FUEL, SEGMENTS, COLORS) VALUES (SEQ_TRUCK.NEXTVAL, 'TGX 18.440', 440, 10518, 'diesel', 'Long haul', 'red,white,blue');

INSERT INTO TRUCK (ID, NAME, ENGINE_HP, ENGINE_VOLUME, FUEL, SEGMENTS, COLORS) VALUES (SEQ_TRUCK.NEXTVAL, 'TGX 18.320', 320, 10518, 'diesel', 'Wastedisposal', 'white,blue');

commit;