DROP TABLE IF EXISTS TRUCK;

CREATE TABLE TRUCK(
	ID BIGINT NOT NULL,
	NAME VARCHAR(256) NOT NULL,
	ENGINE_HP INTEGER NOT NULL,
	ENGINE_VOLUME VARCHAR NOT NULL,
	FUEL VARCHAR(10) NOT NULL,
	SEGMENTS VARCHAR(256) NOT NULL,
	COLORS VARCHAR(256) DEFAULT NULL
);

CREATE SEQUENCE SEQ_TRUCK START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE UNIQUE INDEX IDX_TRUCK ON TRUCK (ID);
--CREATE UNIQUE INDEX IDX_TRUCK_NAME ON TRUCK (NAME);

ALTER TABLE TRUCK ADD CONSTRAINT PK_TRUCK PRIMARY KEY (ID);
--ALTER TABLE TRUCK ADD CONSTRAINT UN_TRUCK_NAME UNIQUE (NAME);